from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from supabase import Client


BUNDLE_KEYS = (
    "learn_curriculum",
    "shop_catalog",
    "hub_videos",
    "hub_categories",
    "trainer",
    "game",
    "portal_app",
    "landing_copy",
    "legal_pages",
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_bundle(client: Client, key: str) -> dict[str, Any] | None:
    res = client.table("cms_content_bundles").select("*").eq("key", key).maybe_single().execute()
    return res.data


def list_bundles(client: Client) -> list[dict[str, Any]]:
    res = client.table("cms_content_bundles").select("key, updated_at").order("key").execute()
    return list(res.data or [])


def upsert_bundle(client: Client, key: str, payload: Any) -> dict[str, Any]:
    row = {"key": key, "payload": payload, "updated_at": _now_iso()}
    res = client.table("cms_content_bundles").upsert(row, on_conflict="key").execute()
    return res.data[0]


def get_static_root() -> Path:
    env = os.environ.get("CMS_STATIC_ROOT", "").strip()
    if not env:
        try:
            from app.config import get_settings

            s = get_settings()
            if s.cms_static_root:
                env = s.cms_static_root
        except Exception:
            pass
    if env:
        return Path(env)
    here = Path(__file__).resolve()
    backend_root = here.parents[3]
    candidates = [
        backend_root.parent / "9wellcms" / "apps" / "web" / "public" / "v2",
        Path.cwd() / "apps" / "web" / "public" / "v2",
    ]
    for c in candidates:
        if c.exists():
            return c
    fallback = Path.cwd() / "public" / "v2"
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback


def get_seeds_dir() -> Path | None:
    env = os.environ.get("CMS_SEEDS_DIR", "").strip()
    if not env:
        try:
            from app.config import get_settings

            s = get_settings()
            if s.cms_seeds_dir:
                env = s.cms_seeds_dir
        except Exception:
            pass
    if env and Path(env).exists():
        return Path(env)
    here = Path(__file__).resolve()
    backend_root = here.parents[3]  # .../9wellbackend
    candidates = [
        backend_root / "content" / "cms-seeds",
        backend_root.parent / "9wellcms" / "content" / "cms-seeds",
        Path.cwd() / "content" / "cms-seeds",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def seed_bundles_from_files(client: Client, overwrite: bool = True) -> list[str]:
    seeds = get_seeds_dir()
    if not seeds:
        raise FileNotFoundError("CMS seeds directory not found (set CMS_SEEDS_DIR)")
    written: list[str] = []
    for key in BUNDLE_KEYS:
        path = seeds / f"{key}.json"
        if not path.exists():
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not overwrite:
            existing = get_bundle(client, key)
            if existing and existing.get("payload") and existing["payload"] != {}:
                continue
        upsert_bundle(client, key, payload)
        written.append(key)
    return written


def _js_assign(name: str, value: Any) -> str:
    return f"window.{name} = {json.dumps(value, ensure_ascii=False, indent=2)};\n"


def write_learn(root: Path, payload: dict) -> str:
    parts = [
        "// Generated by 9well CMS — do not edit by hand\n",
        _js_assign("NW_TIERS", payload.get("NW_TIERS") or {}),
        _js_assign("NW_TIER_ORDER", payload.get("NW_TIER_ORDER") or []),
        _js_assign("NW_SCALE", payload.get("NW_SCALE") or []),
        _js_assign("NW_WEEKS", payload.get("NW_WEEKS") or []),
        _js_assign("NW_FORMS", payload.get("NW_FORMS") or {}),
        _js_assign("NW_CHECKINS", payload.get("NW_CHECKINS") or {}),
        _js_assign("NW_SUMMARY", payload.get("NW_SUMMARY") or {}),
    ]
    rel = "9well-learn/curriculum.js"
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(parts), encoding="utf-8")
    return rel


def write_shop(root: Path, payload: dict) -> str:
    parts = [
        "// Generated by 9well CMS\n",
        _js_assign("NW_SHOP_DISCLAIMER", payload.get("disclaimer") or ""),
        _js_assign("NW_SHOP_CATS", payload.get("cats") or {}),
        _js_assign("NW_PRODUCTS", payload.get("products") or []),
    ]
    rel = "9well-shop/products.js"
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(parts), encoding="utf-8")
    return rel


def write_hub_videos(root: Path, payload: dict) -> str:
    videos = payload.get("videos") if isinstance(payload, dict) else payload
    if isinstance(videos, dict) and "videos" in videos:
        videos = videos["videos"]
    rel = "9well-hub/videos.js"
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("// Generated by 9well CMS\n" + _js_assign("NINEWELL_VIDEOS", videos or []), encoding="utf-8")
    return rel


def write_hub_cats_into_articles_header(root: Path, cats: dict) -> None:
    """Cats live in articles.js as NINEWELL_CATS — merged in write_hub_articles."""
    pass


def write_hub_articles(root: Path, posts: list[dict], cats: dict) -> str:
    articles = []
    for p in posts:
        articles.append(
            {
                "slug": p.get("slug"),
                "cat": p.get("cat_key") or "co-the",
                "title": p.get("title"),
                "excerpt": p.get("excerpt") or "",
                "author": p.get("author") or "",
                "reviewed": p.get("reviewed") or "",
                "date": (str(p.get("published_at") or "")[:10] or ""),
                "readMin": int(p.get("read_min") or 5),
                "featured": bool(p.get("featured")),
                "tags": p.get("tags") if isinstance(p.get("tags"), list) else [],
                "body": p.get("body_html") or "",
            }
        )
    rel = "9well-hub/articles.js"
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "// Generated by 9well CMS\n"
        + _js_assign("NINEWELL_CATS", cats or {})
        + _js_assign("NINEWELL_ARTICLES", articles)
    )
    path.write_text(text, encoding="utf-8")
    return rel


def write_portal(root: Path, payload: dict) -> str:
    rel = "9well-app/portal-data.js"
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by 9well CMS\n" + _js_assign("NW_PORTAL_DATA", payload or {}),
        encoding="utf-8",
    )
    return rel


def write_trainer(root: Path, payload: dict) -> str:
    rel = "9well-trainer/trainer-data.js"
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by 9well CMS\n" + _js_assign("NW_TRAINER_DATA", payload or {}),
        encoding="utf-8",
    )
    return rel


def write_game(root: Path, payload: dict) -> str:
    rel = "9well-game/game-data.js"
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by 9well CMS\n" + _js_assign("NW_GAME_DATA", payload or {}),
        encoding="utf-8",
    )
    return rel


def publish_all_static(client: Client, blog_posts: list[dict]) -> list[str]:
    root = get_static_root()
    files: list[str] = []

    def payload(key: str) -> dict:
        row = get_bundle(client, key)
        return (row or {}).get("payload") or {}

    learn = payload("learn_curriculum")
    if learn:
        files.append(write_learn(root, learn))

    shop = payload("shop_catalog")
    if shop:
        files.append(write_shop(root, shop))

    videos = payload("hub_videos")
    files.append(write_hub_videos(root, videos))

    cats_row = payload("hub_categories")
    cats = cats_row.get("cats") if isinstance(cats_row, dict) else cats_row
    files.append(write_hub_articles(root, blog_posts, cats or {}))

    portal = payload("portal_app")
    files.append(write_portal(root, portal))

    trainer = payload("trainer")
    files.append(write_trainer(root, trainer))

    game = payload("game")
    files.append(write_game(root, game))

    # landing/legal are API-served; still dump JSON snapshots for deploy tooling
    for key in ("landing_copy", "legal_pages"):
        p = payload(key)
        snap = root / "_cms" / f"{key}.json"
        snap.parent.mkdir(parents=True, exist_ok=True)
        snap.write_text(json.dumps(p, ensure_ascii=False, indent=2), encoding="utf-8")
        files.append(str(snap.relative_to(root)))

    return files
